#!/bin/bash

set -euo pipefail

declare -r dataDir=/data
# Intermediate data dir collecting all files to sync
declare -r tmpDir=/tmp/data

# This is in bytes/s, can use B|K|M|...
declare -r upload_bw=100k
declare -r download_bw=2M

################################################################################
is_db_file() {
    local -r file=${1}

    [[ ${file} =~ ^.+\.sdb$ ]]
}

# We only need to backup
# wview-archive
# wview-conf.
# weewx.conf.
# All the other files are generated.
declare -a filesList=(
    $(find "${dataDir}" \
        -maxdepth 3 \
        -type f \
        -wholename "*/archive/wview-archive.sdb" \
        -or \
        -wholename "*/conf/wview-conf.sdb" \
        -or \
        -wholename "*/conf/weewx.conf" \
        )
)

rm -rf "${tmpDir}"

set -x
for f in "${filesList[@]}"; do
    echo "INFO: backing up ${f}"
    mkdir -p "${tmpDir}"/"$(dirname ${f})"

    if $(is_db_file "${f}"); then
        sqlite3 \
            -cmd ".timeout 10000" \
            "${f}" \
            ".backup ${tmpDir}/${f}"
     else
        install -D "${f}" "${tmpDir}/${f}"
    fi

    bzip2 -z "${tmpDir}/${f}"
done

echo "INFO: files to backup:\n"
find ${tmpDir} -type f

rclone --bwlimit "${upload_bw}":"${download_bw}" sync -P "${tmpDir}" backblaze:weather-station
