---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: nginx
  name: nginx
  namespace: default

spec:
  selector:
    matchLabels:
      app: nginx

  replicas: 1

  template:
    metadata:
      labels:
        app: nginx

    spec:
      hostAliases:
      - ip: "192.168.1.200"
        hostnames:
        - "meteo.local"
        - "meteo"

      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - containerPort: 80

        volumeMounts:
        - name: nginx-cfg
          mountPath: /etc/nginx/conf.d/default.conf
          readOnly: true

        - name: ssl-certs
          mountPath: /etc/letsencrypt
          readOnly: true

        - name: wview-img-fiobbio
          mountPath: /www/wview-img/fiobbio
          readOnly: true

        - name: wview-img-misma
          mountPath: /www/wview-img/misma
          readOnly: true

        - name: webcam
          mountPath: /www/webcam
          readOnly: true

        - name: webshot
          mountPath: /www/webshot
          readOnly: true

        - name: wview-html-static
          mountPath: /weather-station/wview/html/fiobbio
          readOnly: true

        - name: tz-config
          mountPath: /etc/localtime
          readOnly: true

      volumes:
      - name: nginx-cfg
        hostPath:
          path: /home/pi/weather-station/http_server/nginx_cfg
          type: File

      - name: ssl-certs
        hostPath:
          path: /home/pi/secrets/letsencrypt
          type: Directory

      - name: wview-img-fiobbio
        hostPath:
          path: /tmp/wview-data-img/fiobbio
          type: Directory

      - name: wview-img-misma
        hostPath:
          path: /tmp/wview-data-img/misma
          type: Directory

      - name: webcam
        hostPath:
          path: /tmp/webcam
          type: Directory

      - name: webshot
        hostPath:
          path: /tmp/webshot
          type: Directory

      - name: wview-html-static
        hostPath:
          path: /home/pi/weather-station/wview/html/fiobbio
          type: Directory

      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Europe/Rome
          type: File

---
#
# NOTE: this requires:
# minikube start --extra-config=apiserver.service-node-port-range=1-65535
#
apiVersion: v1
kind: Service

metadata:
  name: nginx

spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
  # port here is the internal container port
  - port: 80
    name: http
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    # nodePort here is the external service port
    nodePort: 80

  - port: 443
    name: https
    nodePort: 443
