---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weewx-$WEEWX_INSTANCE_NAME
spec:
  selector:
    matchLabels:
      app: weewx-$WEEWX_INSTANCE_NAME # has to match .spec.template.metadata.labels
  serviceName: weewx-$WEEWX_INSTANCE_NAME
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: weewx-$WEEWX_INSTANCE_NAME # has to match .spec.selector.matchLabels
        station: $WEEWX_INSTANCE_NAME

    spec:
      terminationGracePeriodSeconds: 10
      containers:

      - name: weewx
        image: pullme/weewx:latest

        command: [ "/bin/bash",  "-c" ]
        args:
            - |
                set -x
                [ -e /var/lib/weewx/weewx.sdb ] || ln -s wview-archive.sdb /var/lib/weewx/weewx.sdb
                cp -a /weewx/skins/Seasons/* /etc/weewx/skins/Seasons/
                exec weewxd

        startupProbe:
          # Allow a 2 minutes startup
          periodSeconds: 10
          failureThreshold: 12
          exec:
            # fixme, this is a trueism :-)
            command: ["/bin/bash", "-c", "[ -d /proc/1 ]"]

        livenessProbe:
          # Every 5m, check for liveness.
          # If for 3 times liveness fails, set pod unhealthy.
          # Unhealthy after 15 min
          periodSeconds: 300
          initialDelaySeconds: 600
          timeoutSeconds: 10
          #failureThreshold: 3
          #successThreshold: 1
          exec:
            command: ["/bin/bash", "-c", "exec /weewx/scripts/health-check.sh /var/www/html/weewx"]

        volumeMounts:
        - name: ws-code
          mountPath: /weewx
          subPath: apps/weewx
          readOnly: true

        - name: database
          mountPath: /var/lib/weewx

        - name: weewx-conf
          mountPath: /etc/weewx/weewx.conf
          readOnly: true

        - name: weewx-html
          mountPath: /var/www/html/weewx

        - name: etc-localtime
          mountPath: /etc/localtime
          readOnly: true

      volumes:
      - name: ws-code
        persistentVolumeClaim:
          claimName: ws-code-claim

      - name: database
        hostPath:
          path: /home/pi/station-data/$WEEWX_INSTANCE_NAME/archive
          type: Directory

      - name: weewx-conf
        hostPath:
          path: /home/pi/station-data/$WEEWX_INSTANCE_NAME/conf/weewx.conf
          type: File

      - name: etc-localtime
        hostPath:
          path: /etc/localtime
          type: File

      - name: weewx-html
        hostPath:
          path: /tmp/station-data-img/$WEEWX_INSTANCE_NAME
          type: Directory
