#!/bin/sh
if [ "" != "$4" ]; then
    echo "select value from config where name='$4';" > /etc/wview/cmnd.sql
    echo ".read /etc/wview/cmnd.sql" | sqlite3 /etc/wview/wview-conf.sdb > /etc/wview/value.out
    IS_ENABLED=`cat /etc/wview/value.out`
    rm -rf /etc/wview/cmnd.sql /etc/wview/value.out
else
    IS_ENABLED=yes
fi
if [ "$IS_ENABLED" != "yes" ]; then
    exit 0
fi
NEWVAL=$2
echo "-------------------------------------------------------------"
echo "$3"
echo "PARAMETER: $1"
echo -n "($2): "
read INVAL
if [ "" != "$INVAL" ]; then
    echo "update config set value='$INVAL' where name='$1';" > /etc/wview/cmnd.sql
    echo ".read /etc/wview/cmnd.sql" | sqlite3 /etc/wview/wview-conf.sdb
    rm -rf /etc/wview/cmnd.sql
    if [ "$1" = "STATION_TYPE" ]; then
        if [ "$INVAL" = "VantagePro" ]; then
            echo "wviewd_vpro" > /etc/wview/wview-binary
        else
            if [ "$INVAL" = "WXT510" ]; then
                echo "wviewd_wxt510" > /etc/wview/wview-binary
            else
                if [ "$INVAL" = "WS-2300" ]; then
                    echo "wviewd_ws2300" > /etc/wview/wview-binary
                else
                    if [ "$INVAL" = "WMR918" ]; then
                        echo "wviewd_wmr918" > /etc/wview/wview-binary
                    else
                        if [ "$INVAL" = "WMRUSB" ]; then
                            echo "wviewd_wmrusb" > /etc/wview/wview-binary
                        else
                            if [ "$INVAL" = "WH1080" ]; then
                                echo "wviewd_wh1080" > /etc/wview/wview-binary
                            else
                                if [ "$INVAL" = "Simulator" ]; then
                                    echo "wviewd_sim" > /etc/wview/wview-binary
                                else
                                    if [ "$INVAL" = "TWI" ]; then
                                        echo "wviewd_twi" > /etc/wview/wview-binary
                                    else
                                        if [ "$INVAL" = "TE923" ]; then
                                            echo "wviewd_te923" > /etc/wview/wview-binary
                                        else
                                            if [ "$INVAL" = "Virtual" ]; then
                                                echo "wviewd_virtual" > /etc/wview/wview-binary
                                            fi
                                        fi
                                    fi
                                fi
                            fi
                        fi
                    fi
                fi
            fi
        fi
    fi
fi
