#!/bin/sh

# Esegue lo script dal repository weather_station.
#
# Vedi: https://github.com/marcov/weather_station
#
cd /home/pi/weather_station/webcam || exit $?

# Suppress stdout to avoid cron email notifications...
# echo "Executing delete_old_ftp_pictures.sh..."
./delete_old_ftp_pictures.sh  > /dev/null || exit $?
echo "OK"

cd -

exit 0
