---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backupper
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: backupper
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backupper
              image: pullme/x86_64-rclone:latest
              imagePullPolicy: IfNotPresent
              command: ["/bin/bash", "-c"]
              args:
                - ln -sf /usr/share/zoneinfo/Europe/Rome /etc/localtime; rclone config create backblaze b2 account $BACKBLAZE_ACCOUNT key $BACKBLAZE_KEY; /backupper/run-backup
              env:
                - name: BACKBLAZE_ACCOUNT
                  valueFrom:
                    secretKeyRef:
                      name: backblaze-info
                      key: BACKBLAZE_ACCOUNT
                - name: BACKBLAZE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: backblaze-info
                      key: BACKBLAZE_KEY
              volumeMounts:
                - name: ws-code
                  mountPath: /backupper
                  subPath: apps/backupper
                  readOnly: true
                - name: ws-data
                  mountPath: /station-data
                  readOnly: true
                - name: grafana-data
                  mountPath: /grafana-data
                  readOnly: true
                - name: secrets-data
                  mountPath: /secrets-data
                  readOnly: true
          volumes:
            - name: ws-code
              persistentVolumeClaim:
                claimName: ws-code-claim
            - name: ws-data
              persistentVolumeClaim:
                claimName: ws-data-claim
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-data-claim
            - name: secrets-data
              persistentVolumeClaim:
                claimName: all-secrets-claim
