---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns
  labels:
    app: ddns
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  # The default looks to be 100. Increase it.
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ddns
              image: pullme/x86_64-nc-ddns:latest
              imagePullPolicy: IfNotPresent
              command: ["/nc-ddns.sh", "-d"]
              env:
                - name: NC_DDNS_HOST
                  valueFrom:
                    secretKeyRef:
                      name: ddns-info
                      key: NC_DDNS_HOST
                - name: NC_DDNS_DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: ddns-info
                      key: NC_DDNS_DOMAIN
                - name: NC_DDNS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ddns-info
                      key: NC_DDNS_PASSWORD
              volumeMounts:
                # For weird reasons we cannot mount a single file subpath as R/W
                # (/tmp/ddns-ip)
                - name: ws-shared
                  mountPath: /tmp
                  readOnly: false
          volumes:
            - name: ws-shared
              persistentVolumeClaim:
                claimName: ws-shared-claim
