---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: downloader

spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  # The default looks to be 100. Increase it.
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: downloader
              image: docker.io/library/python:3.12
              imagePullPolicy: IfNotPresent
              command:
              - /downloader/run.sh

              volumeMounts:
                - name: ws-code
                  mountPath: /downloader
                  subPath: apps/downloader
                  readOnly: true

                - name: outdir
                  mountPath: /tmp/downloader
                  readOnly: false

          volumes:
            - name: ws-code
              persistentVolumeClaim:
                  claimName: ws-code-claim

            - name: outdir
              hostPath:
                path: /tmp/downloader
                type: Directory

