apiVersion: v1
kind: PersistentVolume
metadata:
  name: ws-code
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/home/pi/weather-station"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ws-code-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 4Gi
