################################################################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ws-code
  labels:
    name: ws-code
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /home/pi/weather-station
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - meteo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ws-code-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
        name: ws-code
################################################################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ws-data
  labels:
    name: ws-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /home/pi/station-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - meteo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ws-data-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
        name: ws-data
################################################################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ws-shared
  labels:
    name: ws-shared
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  local:
    path: /tmp/k8s-pv-shared
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - meteo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ws-shared-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
        name: ws-shared

################################################################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data
  labels:
    name: grafana-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /home/pi/k8s-pv/grafana-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - meteo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
        name: grafana-data
################################################################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data
  labels:
    name: prometheus-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /home/pi/k8s-pv/prometheus-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - meteo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
        name: prometheus-data
################################################################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: all-secrets
  labels:
    name: all-secrets
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /home/pi/secrets
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - meteo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: all-secrets-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
        name: all-secrets
################################################################################
