apiVersion: batch/v1
kind: CronJob
metadata:
  name: webshot
spec:
  schedule: "17 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure

          hostAliases:
          - ip: "0.0.0.0"
            hostnames:
            - "cdn.privacy-mgmt.com"

          containers:
          - name: webshot
            image: pullme/x86_64-webshot:latest
            imagePullPolicy: IfNotPresent
            args:
            - /webshot/run.sh
            - /webshot-conf/config.json
            - /destdir

            volumeMounts:
            - name: ws-code
              mountPath: /webshot-conf
              subPath: apps/webshot
              readOnly: true

            - name: webshot-destdir
              mountPath: /destdir

          volumes:
          - name: webshot-destdir
            hostPath:
              path: /tmp/webshot
              type: Directory

          - name: ws-code
            persistentVolumeClaim:
                claimName: ws-code-claim

