apiVersion: batch/v1
kind: CronJob
metadata:
  name: wz-svg
spec:
  schedule: "22 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: wz-svg
        spec:
          restartPolicy: OnFailure
          hostAliases:
            - ip: "0.0.0.0"
              hostnames:
                - "www.googletagmanager.com"
          containers:
            - name: wz-svg
              image: pullme/x86_64-wz-svg:latest
              imagePullPolicy: IfNotPresent
              args:
                - /destdir/wz_meteogram.svg
              volumeMounts:
                - name: ws-shared
                  mountPath: /destdir
                  subPath: webshot
                  readOnly: false
          volumes:
            - name: ws-shared
              persistentVolumeClaim:
                claimName: ws-shared-claim
