#!/bin/bash

set -euo pipefail

wviewDataPath=/wview-data
destDir="/data"

# We only need to backup wview-archive and wview-conf. All the other files are
# generated.
declare -a filesList=(
    $(find "${wviewDataPath}" \
        -maxdepth 3 \
        -type f \
        -wholename "*/archive/wview-archive.sdb" \
        -or \
        -wholename "*/conf/wview-conf.sdb" \
        )
)

rm -rf "${destDir}"

set -x
for f in "${filesList[@]}"; do
    echo "INFO: backing up ${f}"
    mkdir -p "${destDir}"/"$(dirname ${f})"
    sqlite3 \
        -cmd ".timeout 10000" \
        "${f}" \
        ".backup ${destDir}/${f}"

    bzip2 -z "${destDir}/${f}"
done

echo "INFO: files to backup:\n"
find ${destDir} -type f

rclone sync -P "${destDir}" backblaze:weather-station
