#!/bin/bash

set -euo pipefail

wviewDataPath=/station-data
destDir="/data"

is_db_file() {
    local -r file=${1}

    [[ ${file} =~ ^.+\.sdb$ ]]
}

# We only need to backup
# wview-archive
# wview-conf.
# weewx.conf.
# All the other files are generated.
declare -a filesList=(
    $(find "${wviewDataPath}" \
        -maxdepth 3 \
        -type f \
        -wholename "*/archive/wview-archive.sdb" \
        -or \
        -wholename "*/conf/wview-conf.sdb" \
        -or \
        -wholename "*/conf/weewx.conf" \
        )
)

rm -rf "${destDir}"

set -x
for f in "${filesList[@]}"; do
    echo "INFO: backing up ${f}"
    mkdir -p "${destDir}"/"$(dirname ${f})"

    if $(is_db_file "${f}"); then
        sqlite3 \
            -cmd ".timeout 10000" \
            "${f}" \
            ".backup ${destDir}/${f}"
     else
        install -D "${f}" "${destDir}/${f}"
    fi

    bzip2 -z "${destDir}/${f}"
done

echo "INFO: files to backup:\n"
find ${destDir} -type f

rclone sync -P "${destDir}" backblaze:weather-station
